//Artists
export const SET_ARTISTS = 'SET_ARTISTS';
export const FETCH_ARTISTS_FAILED = 'FETCH_ARTISTS_FAILED';
export const FETCH_ARTISTS_START = 'FETCH_ARTISTS_START';
export const SAVE_ARTIST_START = 'SAVE_ARTIST_START';
export const SAVE_ARTIST_SUCCESS = 'SAVE_ARTIST_SUCCESS';
export const SAVE_ARTIST_FAILED = 'SAVE_ARTIST_FAILED';
export const GET_ARTIST_BY_ID_START = 'GET_ARTIST_BY_ID_START';
export const SET_ARTIST_BY_ID = 'SET_ARTIST_BY_ID';
export const GET_ARTIST_BY_ID_FAILED = 'GET_ARTIST_BY_ID_FAILED';
export const DELETE_ARTIST_BY_ID_START = 'DELETE_ARTIST_BY_ID_START';
export const DELETE_ARTIST_BY_ID_SUCCESS = 'DELETE_ARTIST_BY_ID_SUCCESS';
export const DELETE_ARTIST_BY_ID_FAILED = 'DELETE_ARTIST_BY_ID_FAILED';
export const UPDATE_ARTIST_BY_ID_START = 'UPDATE_ARTIST_BY_ID_START';
export const UPDATE_ARTIST_BY_ID_SUCCESS = 'UPDATE_ARTIST_BY_ID_SUCCESS';
export const UPDATE_ARTIST_BY_ID_FAILED = 'UPDATE_ARTIST_BY_ID_FAILED';

export const SET_STYLES = 'SET_STYLES';
export const FETCH_STYLES_FAILED = 'FETCH_STYLES_FAILED';
export const FETCH_STYLES_START = 'FETCH_STYLES_START';
export const SAVE_STYLE_START = 'SAVE_STYLE_START';
export const SAVE_STYLE_SUCCESS = 'SAVE_STYLE_SUCCESS';
export const SAVE_STYLE_FAILED = 'SAVE_STYLE_FAILED';

export const SET_NATIONALITIES = 'SET_NATIONALITIES';
export const FETCH_NATIONALITIES_FAILED = 'FETCH_NATIONALITIES_FAILED';
export const FETCH_NATIONALITIES_START = 'FETCH_NATIONALITIES_START';
export const SAVE_NATIONALITY_START = 'SAVE_NATIONALITY_START';
export const SAVE_NATIONALITY_SUCCESS = 'SAVE_NATIONALITY_SUCCESS';
export const SAVE_NATIONALITY_FAILED = 'SAVE_NATIONALITY_FAILED';

export const SET_RECORDS_TEST = 'SET_RECORDS_TEST';
export const FETCH_RECORDS_TEST_START = 'FETCH_RECORDS_TEST_START';

export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';

//Records
export const SET_RECORDS = 'SET_RECORDS';
export const FETCH_RECORDS_FAILED = 'FETCH_RECORDS_FAILED';
export const FETCH_RECORDS_START = 'FETCH_RECORDS_START';
export const SAVE_RECORD_START = 'SAVE_RECORD_START';
export const SAVE_RECORD_SUCCESS = 'SAVE_RECORD_SUCCESS';
export const SAVE_RECORD_FAILED = 'SAVE_RECORD_FAILED';
export const GET_RECORD_BY_ID_START = 'GET_RECORD_BY_ID_START';
export const SET_RECORD_BY_ID = 'SET_RECORD_BY_ID';
export const GET_RECORD_BY_ID_FAILED = 'GET_RECORD_BY_ID_FAILED';
export const DELETE_RECORD_BY_ID_START = 'DELETE_RECORD_BY_ID_START';
export const DELETE_RECORD_BY_ID_SUCCESS = 'DELETE_RECORD_BY_ID_SUCCESS';
export const DELETE_RECORD_BY_ID_FAILED = 'DELETE_RECORD_BY_ID_FAILED';
export const UPDATE_RECORD_BY_ID_START = 'UPDATE_RECORD_BY_ID_START';
export const UPDATE_RECORD_BY_ID_SUCCESS = 'UPDATE_RECORD_BY_ID_SUCCESS';
export const UPDATE_RECORD_BY_ID_FAILED = 'UPDATE_RECORD_BY_ID_FAILED';